# Base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy only necessary files
COPY . .

# Install dependencies
RUN npm ci

# Expose port
EXPOSE 3001

# Start the app
CMD ["node", "server/server.js"]
